service: blogs

provider:
  name: aws
  runtime: python3
  stage: dev
  region: us-east-1
  memorySize: 128
plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    app: run.app
    packRequirements: false
functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'